[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | env
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
known_first_party = ["chess_backend"]
skip_glob = [
    "env/*",
    ".venv/*",
    "build/*",
    "dist/*",
    ".eggs/*",
    "*.egg-info/*",
]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
exclude = [
    "env/.*",
    "\\.venv/.*",
    "build/.*",
    "dist/.*",
    "\\.eggs/.*",
    ".*\\.egg-info/.*",
]
explicit_package_bases = true
namespace_packages = true

# Per-module options
[[tool.mypy.overrides]]
module = [
    "chess.*",
    "streamlit.*",
    "supabase.*",
]
ignore_missing_imports = true 