name: Call Supabase scheduled-sync every day at midnight UTC

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  call-scheduled-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke scheduled-sync
        env:
          SB_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}   # already in your repo secrets
        run: |
          curl -f -w '\nHTTP %{http_code}\n' \
            -X POST \
            -H "apikey: $SB_KEY" \
            -H "Authorization: Bearer $SB_KEY" \
            https://fsmtmtconmgujlhmkqgp.functions.supabase.co/scheduled-sync
