name: Call Supabase scheduled-sync every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (UTC)
  workflow_dispatch:

jobs:
  call-scheduled-sync:
    runs-on: ubuntu-latest
    env:
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
    steps:
      - name: Invoke scheduled-sync
        env:
          SB_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}   # already in your repo secrets
        run: |
          curl -f -w '\nHTTP %{http_code}\n' \
            -X POST \
            -H "apikey: $SB_KEY" \
            -H "Authorization: Bearer $SB_KEY" \
            https://fsmtmtconmgujlhmkqgp.functions.supabase.co/scheduled-sync
