name: Call Supabase scheduled-sync every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (UTC)

jobs:
  call-scheduled-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          set -e
          response=$(curl -s -w "%{http_code}" -o response.txt -X POST "https://fsmtmtconmgujlhmkqgp.functions.supabase.co/scheduled-sync")
          cat response.txt
          if [ "$response" -lt 200 ] || [ "$response" -ge 300 ]; then
            echo "Request failed with status code $response"
            exit 1
          fi