name: Call Supabase scheduled-sync every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (UTC)

jobs:
  call-scheduled-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST "https://fsmtmtconmgujlhmkqgp.functions.supabase.co/scheduled-sync"